[project]
name = "agentic-interview-coach"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mayaannkkk", email = "goyalmayank492@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
agentic-interview-coach = "agentic_interview_coach:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
